name: Bug Report
description: Report a bug to help us improve LLM4S
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: "The application crashes when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug.
      placeholder: |
        1. Set up environment with...
        2. Run command...
        3. Observe error...
      value: "1. \n2. \n3. "
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "The function should return..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Instead, the following error occurs..."
    validations:
      required: true

  - type: checkboxes
    id: impact_areas
    attributes:
      label: Impact Areas
      description: Select any that apply (leave blank if unsure).
      options:
        - label: API / Compatibility
        - label: Security / Privacy
        - label: Reliability / Availability
        - label: Performance
        - label: Documentation
        - label: Unsure

  - type: textarea
    id: error_logs
    attributes:
      label: Error Logs / Stack Trace
      description: Please provide any error messages, stack traces, or relevant log output.
      placeholder: "Paste stack trace or error logs here..."
      render: "scala"

  - type: dropdown
    id: scala_version
    attributes:
      label: Scala Version
      description: Which Scala version are you using?
      options:
        - "2.13.16"
        - "3.7.1"
        - "3.6.x"
        - "Other (please specify below)"
    validations:
      required: true

  - type: dropdown
    id: jdk_version
    attributes:
      label: JDK Version
      description: Which JDK version are you using?
      options:
        - "JDK 21"
        - "JDK 20"
        - "JDK 19"
        - "JDK 17 (LTS)"
        - "Other (please specify below)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Linux"
        - "macOS"
        - "Windows"
        - "Other (please specify below)"
    validations:
      required: true

  - type: textarea
    id: os_details
    attributes:
      label: OS Details (if other)
      description: If you selected "Other" above, please specify your OS version.
      placeholder: "e.g., Ubuntu 22.04 LTS, macOS 13.5, Windows 11 22H2"

  - type: dropdown
    id: llm_provider
    attributes:
      label: LLM Provider
      description: Which LLM provider are you using?
      options:
        - "OpenAI"
        - "Anthropic"
        - "Azure OpenAI"
        - "Google Gemini"
        - "Ollama (local)"
        - "Other (please specify below)"
    validations:
      required: true

  - type: textarea
    id: model_info
    attributes:
      label: Model Information
      description: Provide the specific model name and version.
      placeholder: "e.g., gpt-4o, claude-sonnet-4-5-latest, gemini-2.0-flash"
    validations:
      required: true

  - type: textarea
    id: llm4s_version
    attributes:
      label: LLM4S Version
      description: Which LLM4S version are you using? (Check your build.sbt or dependencies)
      placeholder: "e.g., 0.1.0-SNAPSHOT, 0.0.1"
    validations:
      required: true

  - type: textarea
    id: code_snippet
    attributes:
      label: Code Snippet
      description: Please provide a minimal code example that reproduces the bug.
      placeholder: "Paste a minimal reproducible example here..."
      render: "scala"

  - type: textarea
    id: configuration
    attributes:
      label: Configuration (if relevant)
      description: Provide any relevant configuration. **Please anonymize API keys and sensitive data.**
      placeholder: "LLM_MODEL=openai/gpt-4o\nTRACING_MODE=console\n..."
      render: "bash"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context that might help us understand the issue?
      placeholder: "Add any other relevant information here..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm that you have completed the following.
      options:
        - label: I have searched existing issues and found no duplicates
          required: true
        - label: I have provided all required environment information
          required: true
        - label: I have provided a minimal reproducible example
          required: true
        - label: I have anonymized any sensitive data (API keys, etc.)
          required: true
