repos:
  - repo: https://github.com/softwaremill/scala-pre-commit-hooks
    rev: v0.5.0  # pin a stable version
    hooks:
      - id: sbt-scalafmt-apply
        args: [--non-interactive]
      - id: sbt-fatal-warnings
      - id: sbt-unused-imports

default_stages: [commit, push]
