#!/usr/bin/env bash
# Checks every internal link in docs/**/*.md against the pages the docs site really serves, with a committed
# baseline of known-broken links that can only shrink.
#
# A link passes when the site serves its target. The rules below were checked against https://llm4s.org with
# curl on 2026-10-07 unless marked UNVERIFIED:
#   - A page with front matter is rendered at /path/name.html and also at /path/name; /path/name/ and
#     /path/name.md are 404. An index.md is served at /dir/ (and /dir, which redirects), /dir/index.html and
#     /dir/index - so `[x](index)` on a sibling page works, and /index serves the root (checked 2026-10-08);
#     /path/name/index for a page that is not an index is 404. A `permalink:` in the front matter replaces
#     the URL, and a permalink ending in `/` is served at its `index` and `index.html` too. The site is built by plain Jekyll 3.9 (docs/Gemfile), without
#     jekyll-relative-links, so a `.md` link to a rendered page is NOT rewritten and returns 404.
#   - A .md file WITHOUT front matter is not rendered: Jekyll copies it, so it is served raw at its .md URL
#     and 404s without the extension (docs/reference/migration.md, MODEL_METADATA.md). A link to it is
#     reported as `no-front-matter`: even the working `.md` form shows raw Markdown.
#   - Any other file under docs/ (images, CNAME) is served at its path. Directories and files starting with
#     `_` or `.` and the names under `exclude:` in _config.yml are not served.
#   - Links INSIDE a page without front matter are not clickable on the site (the raw text is shown) and are read on
#     GitHub, so they are checked the way GitHub resolves them: relative to the file, the target file or directory
#     must exist (anywhere in the repository), and the anchor of a Markdown target must exist. A link starting
#     with `/` passes when it names a repository file or a page of the site.
#   - /scaladoc/ is generated by the Pages workflow (sbt docs/doc) and exists only on the deployed site.
#   - Relative links resolve against the page's URL, not its source directory (a page with a permalink
#     differs from its path).
#   - Anchors: heading ids follow the GitHub-style rule (lower case, punctuation dropped, spaces to hyphens,
#     -1/-2 for repeats), plus kramdown `{#id}` and HTML id=/name= attributes. UNVERIFIED for headings that
#     contain HTML or unusual Unicode; Setext (underlined) headings are not read.
#   - Targets containing Liquid ({{ }} or {% %}) cannot be resolved here and are skipped.
#
# Each broken link has a cause: page-missing (no such page), repo-source (the link leaves docs/ and points at a
# repository file: fine on GitHub, dead on the site), stale-anchor, no-front-matter, md-extension.
#
# The baseline (scripts/docs-link-baseline.txt) lists one `file -> target` key per known-broken link, without
# line numbers so unrelated edits do not change it. The check FAILS when
#   - a link is broken and not in the baseline (a new broken link), or
#   - a baseline entry is no longer broken (delete it: the baseline only shrinks).
#
# Usage: scripts/check-docs-site-links.sh [--root DIR] [--baseline FILE] [--print | --update-baseline]
#   (no flag)          check; exit 0 when the broken links equal the baseline, 1 on any difference, 2 on a usage error
#   --print            print every broken link as `file -> target<TAB>cause` and exit 0 (maintainers: what is broken now)
#   --update-baseline  rewrite the baseline from the current tree and exit 0 (review the diff before committing)
#   --root DIR         the docs directory (default: docs/ of this repository)
#   --baseline FILE    the baseline file (default: scripts/docs-link-baseline.txt)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export CHECK_REPO_ROOT="$REPO_ROOT"
exec python3 - "$@" <<'PYEOF'
import os
import posixpath
import re
import sys

REPO_ROOT = os.environ["CHECK_REPO_ROOT"]
GENERATED_PREFIXES = ("/scaladoc",)
SKIP_SCHEMES = ("http://", "https://", "mailto:", "tel:", "javascript:", "data:", "//", "ftp://")


def usage_error(message):
    sys.stderr.write("check-docs-site-links: %s\n" % message)
    sys.exit(2)


def parse_args(argv):
    opts = {"root": os.path.join(REPO_ROOT, "docs"),
            "baseline": os.path.join(REPO_ROOT, "scripts", "docs-link-baseline.txt"),
            "mode": "check"}
    i = 0
    while i < len(argv):
        a = argv[i]
        if a in ("--root", "--baseline"):
            if i + 1 >= len(argv):
                usage_error("%s needs a value" % a)
            opts[a[2:]] = argv[i + 1]
            i += 2
        elif a == "--print":
            opts["mode"] = "print"
            i += 1
        elif a == "--update-baseline":
            opts["mode"] = "update"
            i += 1
        else:
            usage_error("unknown argument %s" % a)
    return opts


def read_excludes(root):
    names = set()
    cfg = os.path.join(root, "_config.yml")
    if not os.path.isfile(cfg):
        return names
    inside = False
    with open(cfg, encoding="utf-8") as f:
        for line in f:
            if re.match(r"^exclude:\s*$", line):
                inside = True
                continue
            if inside:
                m = re.match(r"^\s+-\s*(\S+?)/?\s*$", line)
                if m:
                    names.add(m.group(1))
                else:
                    inside = False
    return names


def front_matter(text):
    """Return (has_front_matter, front_matter_text)."""
    m = re.match(r"^---[ \t]*\r?\n(.*?)\r?\n---[ \t]*(\r?\n|$)", text, re.DOTALL)
    return (True, m.group(1)) if m else (False, "")


def blank_code(text, inline=True):
    """Blank fenced code blocks (and inline code spans when `inline`), keeping every newline so line numbers
    survive. Headings keep their inline code: the heading id is made from its text."""
    out = []
    fence = None
    for line in text.split("\n"):
        stripped = line.lstrip()
        marker = stripped[:3]
        if fence is None and marker in ("```", "~~~"):
            fence = marker
            out.append("")
            continue
        if fence is not None:
            if stripped.startswith(fence):
                fence = None
            out.append("")
            continue
        out.append(re.sub(r"`[^`\n]*`", lambda m: " " * len(m.group(0)), line) if inline else line)
    return "\n".join(out)


def slugify(heading):
    text = re.sub(r"\{[:#][^}]*\}\s*$", "", heading)
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = text.replace("`", "").replace("*", "")
    text = text.strip().lower()
    text = re.sub(r"[^\w\- \ufe0f]", "", text, flags=re.UNICODE)  # the site keeps the emoji variation selector
    return text.replace(" ", "-")


def page_anchors(text):
    anchors = set()
    seen = {}
    stripped = blank_code(text, inline=False)
    for line in stripped.split("\n"):
        m = re.match(r"^(#{1,6})[ \t]+(.*?)[ \t]*#*[ \t]*$", line)
        if not m:
            continue
        body = m.group(2)
        explicit = re.search(r"\{:?\s*#([A-Za-z0-9_\-:.]+)[^}]*\}\s*$", body)
        if explicit:
            anchors.add(explicit.group(1))
            continue
        slug = slugify(body)
        if not slug:
            continue
        count = seen.get(slug, 0)
        seen[slug] = count + 1
        anchors.add(slug if count == 0 else "%s-%d" % (slug, count))
    for m in re.finditer(r"""<[a-zA-Z][^>]*\b(?:id|name)\s*=\s*["']([^"']+)["']""", stripped):
        anchors.add(m.group(1))
    for m in re.finditer(r"\{:?\s*#([A-Za-z0-9_\-:.]+)[^}]*\}", stripped):
        anchors.add(m.group(1))
    return anchors


class Site(object):
    def __init__(self, root):
        self.root = root
        self.name = os.path.basename(os.path.abspath(root))
        excludes = read_excludes(root)
        self.rendered = {}   # canonical url -> page record
        self.urls = {}       # every accepted url -> page record
        self.raw = {}        # url (with extension) -> source rel path, for md without front matter
        self.raw_noext = {}  # url without .md -> source rel path
        self.assets = set()
        self.sources = {}    # source rel path -> page record (rendered or raw)
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = sorted(d for d in dirnames
                                 if not d.startswith(("_", ".")) and d not in excludes)
            for fn in sorted(filenames):
                if fn.startswith(("_", ".")) or fn in excludes:
                    continue
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, root).replace(os.sep, "/")
                if fn.endswith((".md", ".markdown")):
                    with open(full, encoding="utf-8", errors="replace") as f:
                        text = f.read()
                    has_fm, fm = front_matter(text)
                    rec = {"rel": rel, "text": text, "rendered": has_fm, "anchors": None}
                    self.sources[rel] = rec
                    if has_fm:
                        self._add_rendered(rec, fm)
                    else:
                        self.raw["/" + rel] = rel
                        self.raw_noext["/" + re.sub(r"\.(md|markdown)$", "", rel)] = rel
                else:
                    self.assets.add("/" + rel)

    def _add_rendered(self, rec, fm):
        rel = rec["rel"]
        stem = re.sub(r"\.(md|markdown)$", "", rel)
        perm = re.search(r"^permalink:\s*['\"]?([^'\"\s]+)['\"]?\s*$", fm, re.MULTILINE)
        if perm:
            canonical = perm.group(1)
            if not canonical.startswith("/"):
                canonical = "/" + canonical
            accepted = {canonical}
            if canonical.endswith("/"):
                accepted.add(canonical.rstrip("/") or "/")
                accepted.add(canonical + "index.html")
                accepted.add(canonical + "index")  # /dir/index is served too, including /index for the root
            else:
                accepted.add(canonical + ".html")
        elif posixpath.basename(stem) == "index":
            directory = "/" + posixpath.dirname(stem)
            directory = directory if directory.endswith("/") else directory + "/"
            canonical = directory
            accepted = {directory, directory + "index.html", directory + "index"}
            if directory != "/":
                accepted.add(directory.rstrip("/"))
        else:
            canonical = "/" + stem + ".html"
            accepted = {canonical, "/" + stem}
        rec["url"] = canonical
        self.rendered[canonical] = rec
        for u in accepted:
            self.urls[u] = rec

    def anchors(self, rec):
        if rec["anchors"] is None:
            rec["anchors"] = page_anchors(rec["text"])
        return rec["anchors"]


def extract_links(text):
    """Yield (line, target) for each link-like reference outside code."""
    cleaned = blank_code(text)
    out = []
    patterns = [
        re.compile(r"\]\(\s*<?([^)\s>]+)>?(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\)"),
        re.compile(r"^\s{0,3}\[[^\]]+\]:\s*<?(\S+?)>?(?:\s+.*)?$", re.MULTILINE),
        re.compile(r"""\b(?:href|src)\s*=\s*["']([^"']+)["']"""),
    ]
    for rx in patterns:
        for m in rx.finditer(cleaned):
            line = cleaned.count("\n", 0, m.start(1)) + 1
            out.append((line, m.group(1).strip()))
    return out


def resolve(site, page, target):
    """Return None when the link is fine, else a cause."""
    if target.startswith(SKIP_SCHEMES) or "{{" in target or "{%" in target:
        return None
    base, _, fragment = target.partition("#")
    base = base.partition("?")[0]
    if base == "":
        if fragment in ("", "top"):
            return None
        return None if fragment in site.anchors(page) else "stale-anchor"
    page_url = page["url"] if page["rendered"] else "/" + page["rel"]
    directory = page_url if page_url.endswith("/") else page_url.rsplit("/", 1)[0] + "/"
    if base.startswith("/"):
        url = posixpath.normpath(base)
    else:
        url = posixpath.normpath(posixpath.join(directory, base))
    if base.endswith("/") and not url.endswith("/"):
        url += "/"
    if not base.startswith("/") and climbs_above_root(directory, base):
        # a browser clamps `/..` to `/`, so on the site this lands on a page of the root, not on the repository
        return "repo-source" if leaves_docs_to_repo(site, page, base) else "page-missing"
    for prefix in GENERATED_PREFIXES:
        if url == prefix or url.startswith(prefix + "/"):
            return None
    if url in site.urls:
        rec = site.urls[url]
        if fragment and fragment != "top" and fragment not in site.anchors(rec):
            return "stale-anchor"
        return None
    if url in site.assets:
        return None
    if url in site.raw or url in site.raw_noext:
        return "no-front-matter"
    if re.search(r"\.(md|markdown)$", url):
        stem = re.sub(r"\.(md|markdown)$", "", url)
        if stem in site.urls or stem + ".html" in site.rendered:
            return "md-extension"
    if leaves_docs_to_repo(site, page, base):
        return "repo-source"
    return "page-missing"


def climbs_above_root(directory, base):
    """True when a relative link has more `..` than the page's URL directory has levels."""
    depth = len([s for s in directory.split("/") if s])
    for segment in base.partition("#")[0].partition("?")[0].split("/"):
        if segment == "..":
            depth -= 1
            if depth < 0:
                return True
        elif segment not in ("", "."):
            depth += 1
    return False


def leaves_docs_to_repo(site, page, base):
    """True when the link, read as a source-relative path, names an existing file or directory outside docs/."""
    if base.startswith("/"):
        return False
    source_dir = posixpath.dirname(page["rel"])
    joined = posixpath.normpath(posixpath.join(source_dir, base))
    if not (joined == ".." or joined.startswith("../")):
        return False
    repo_path = os.path.normpath(os.path.join(site.root, joined))
    return os.path.exists(repo_path)


_FILE_ANCHORS = {}


def anchors_of_file(path):
    if path not in _FILE_ANCHORS:
        with open(path, encoding="utf-8", errors="replace") as f:
            _FILE_ANCHORS[path] = page_anchors(f.read())
    return _FILE_ANCHORS[path]


def resolve_raw(site, page, target):
    """Resolve a link found in a page without front matter the way GitHub does. None when it is fine."""
    if target.startswith(SKIP_SCHEMES) or "{{" in target or "{%" in target:
        return None
    base, _, fragment = target.partition("#")
    base = base.partition("?")[0]
    if base == "":
        if fragment in ("", "top"):
            return None
        return None if fragment in site.anchors(page) else "stale-anchor"
    repo_root = os.path.dirname(os.path.abspath(site.root))
    if base.startswith("/"):
        candidate = os.path.normpath(os.path.join(repo_root, base.lstrip("/")))
        if not os.path.exists(candidate):
            return resolve(site, page, target)
    else:
        source_dir = os.path.dirname(os.path.join(site.root, page["rel"]))
        candidate = os.path.normpath(os.path.join(source_dir, base))
        if not os.path.exists(candidate):
            return "page-missing"
    if fragment and fragment != "top" and os.path.isfile(candidate) and candidate.endswith((".md", ".markdown")):
        return None if fragment in anchors_of_file(candidate) else "stale-anchor"
    return None


def collect(site):
    broken = {}
    for rel, page in sorted(site.sources.items()):
        for line, target in extract_links(page["text"]):
            cause = (resolve if page["rendered"] else resolve_raw)(site, page, target)
            if cause is None:
                continue
            key = "%s/%s -> %s" % (site.name, rel, target)
            if key not in broken:
                broken[key] = (cause, line)
    return broken


def read_baseline(path):
    if not os.path.isfile(path):
        return set()
    keys = set()
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line and not line.startswith("#"):
                keys.add(line)
    return keys


HEADER = """# Known-broken internal links in docs/, one `file -> target` per line (sorted, no line numbers).
# Checked by scripts/check-docs-site-links.sh, which fails on a broken link that is not listed here AND on a
# listed link that no longer breaks: fix a link, then delete its line. Never add a line to hide a new link.
# Regenerate with `scripts/check-docs-site-links.sh --update-baseline` and review the diff.
"""


def main():
    opts = parse_args(sys.argv[1:])
    if not os.path.isdir(opts["root"]):
        usage_error("not a directory: %s" % opts["root"])
    site = Site(opts["root"])
    broken = collect(site)
    if opts["mode"] == "print":
        for key in sorted(broken):
            print("%s\t%s" % (key, broken[key][0]))
        return 0
    if opts["mode"] == "update":
        with open(opts["baseline"], "w", encoding="utf-8") as f:
            f.write(HEADER)
            for key in sorted(broken):
                f.write(key + "\n")
        print("wrote %d entries to %s" % (len(broken), opts["baseline"]))
        return 0
    baseline = read_baseline(opts["baseline"])
    new = sorted(k for k in broken if k not in baseline)
    stale = sorted(k for k in baseline if k not in broken)
    for key in new:
        cause, line = broken[key]
        rel, _, target = key.partition(" -> ")
        print("NEW BROKEN LINK %s:%d -> %s (%s)" % (rel, line, target, cause))
    for key in stale:
        print("STALE BASELINE ENTRY, remove this baseline entry: %s (this link no longer breaks)" % key)
    if new or stale:
        print("%d new broken link(s), %d stale baseline entr(y/ies); %d link(s) known broken"
              % (len(new), len(stale), len(baseline) - len(stale)))
        return 1
    print("docs links OK: %d known-broken link(s) in the baseline, none new" % len(baseline))
    return 0


sys.exit(main())
PYEOF
