source 'https://rubygems.org'

# Ruby 3.4+ compatibility
gem "base64"
gem "csv"
gem "bigdecimal"

gem "jekyll", "~> 3.9"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.7"

gem "just-the-docs", "~> 0.10"

group :jekyll_plugins do
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag", "~> 2.8"
end