name: Release

on:
  push:
    tags:
      - "v[0-9]*"

jobs:
  # Run CI checks first
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read

  publish:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # For trusted publishing
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for sbt-dynver
      
      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "sbt"
      
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      
      - name: Import GPG key
        run: |
          echo "${{ secrets.PGP_SECRET }}" | base64 --decode | gpg --batch --import
          echo "GPG keys imported:"
          gpg --list-secret-keys
      
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          sbt "workspaceRunner/Docker/publishLocal"
          # The Docker plugin builds with the version tag, not 'latest'
          docker tag llm4s/workspace-runner:${VERSION#v} ghcr.io/${{ github.repository_owner }}/workspace-runner:latest
          docker tag llm4s/workspace-runner:${VERSION#v} ghcr.io/${{ github.repository_owner }}/workspace-runner:${VERSION#v}
          docker push ghcr.io/${{ github.repository_owner }}/workspace-runner:${VERSION#v}
          docker push ghcr.io/${{ github.repository_owner }}/workspace-runner:latest